package MainApp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.konek_nasabah;
/**
 *
 * @author Panji Arief
 */
public class Pencairan extends javax.swing.JInternalFrame {
    
        public Pencairan() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbJK = new javax.swing.JComboBox<>();
        txtPK = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNIK = new javax.swing.JTextField();
        txtKerja = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbTenor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        txtBpkb = new javax.swing.JTextField();
        txtStnk = new javax.swing.JTextField();
        txtKendaraan = new javax.swing.JTextField();
        txtNopol = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAngsuran = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbSurvey = new javax.swing.JComboBox<>();
        cbKolektor = new javax.swing.JComboBox<>();
        btnInput = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtPinjam = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTempo = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("No. PK");

        jLabel2.setText("Nama");

        jLabel3.setText("NIK");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Alamat");

        jLabel6.setText("Pekerjaan");

        cbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));

        txtKerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKerjaActionPerformed(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jLabel7.setText("Jumlah Pinjaman");

        jLabel8.setText("Tenor");

        cbTenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 Bulan", "12 Bulan", "18 Bulan" }));

        jLabel9.setText("No. Polisi");

        jLabel10.setText("Tipe Kendaraan");

        jLabel11.setText("Tahun Kendaraan");

        jLabel12.setText("No. BPKB ");

        jLabel13.setText("Nama STNK");

        txtStnk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStnkActionPerformed(evt);
            }
        });

        jLabel14.setText("Angsuran");

        txtAngsuran.setText("Rp. ");

        jLabel15.setText("No. Telp");

        jLabel16.setText("Surveyor");

        jLabel17.setText("Collector");

        cbSurvey.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "020 Fahmi Hakiki", "021 Panji Arief", "022 Hadi Cahyanto" }));
        cbSurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSurveyActionPerformed(evt);
            }
        });

        cbKolektor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "030 Agung Kurniawan", "031 Teddy Budiman" }));

        btnInput.setText("INPUT");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        btnReset.setText("TAMBAH");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtPinjam.setText("Rp. ");

        jLabel18.setText("Jatuh Tempo");

        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel15))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNama)
                                        .addComponent(txtNIK)
                                        .addComponent(cbJK, 0, 168, Short.MAX_VALUE)
                                        .addComponent(txtTelp))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPK, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCari))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel18)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPinjam)
                                    .addComponent(cbTenor, 0, 168, Short.MAX_VALUE)
                                    .addComponent(txtAngsuran)
                                    .addComponent(txtKerja)
                                    .addComponent(jTempo))))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNopol, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtBpkb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(txtTahun, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(cbSurvey, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbKolektor, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStnk, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(0, 43, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtNopol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtBpkb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStnk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbSurvey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKolektor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset)
                            .addComponent(btnInput)
                            .addComponent(btnUpdate))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbTenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 14, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKerjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKerjaActionPerformed

    private void cbSurveyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSurveyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSurveyActionPerformed

    private void txtStnkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStnkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStnkActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        //input data dari form ke database nasabah
        
        String pk = txtPK.getText();
        String nama = txtNama.getText();
        String nik = txtNIK.getText();
        String telp = txtTelp.getText();
        String alamat = txtAlamat.getText();
        String kerja = txtKerja.getText();
        String pinjam = txtPinjam.getText();
        String angsuran = txtAngsuran.getText();
        String nopol = txtNopol.getText();
        String kendaraan = txtKendaraan.getText();
        String tahun = txtTahun.getText();
        String bpkb = txtBpkb.getText();
        String stnk = txtStnk.getText();
        String jeniskelamin =  (String) cbJK.getSelectedItem();
        String tenor =  (String) cbTenor.getSelectedItem();
        String surveyor =  (String) cbSurvey.getSelectedItem();
        String kolektor =  (String) cbKolektor.getSelectedItem();
        String tempo = jTempo.getText();
        
        try{
            
            String sql = " INSERT INTO nasabah VALUES ('"+pk+"','"+nama+"','"+nik+"','"+jeniskelamin+"','"+telp+"','"+alamat+"','"+kerja+"','"+pinjam+"','"+tenor+"','"+angsuran+"','"+tempo+"','"+nopol+"','"+kendaraan+"','"+tahun+"','"+bpkb+"','"+stnk+"','"+surveyor+"','"+kolektor+"');";
            Connection con = (Connection) konek_nasabah.GetConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        }catch (Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Reset Form input data
        
        txtPK.setText("");
        txtNama.setText("");
        txtNIK.setText("");
        txtTelp.setText("");
        txtAlamat.setText("");
        txtKerja.setText("");
        txtPinjam.setText("Rp. ");
        txtAngsuran.setText("Rp. ");
        txtNopol.setText("");
        txtKendaraan.setText("");
        txtTahun.setText("");
        txtBpkb.setText("");
        txtStnk.setText("");
        jTempo.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // Cari data nasabah berdasarkan nomor pk
        
        try {                
                String sql = " SELECT * FROM nasabah WHERE no_pk like '%"+txtPK.getText()+"%'";
                Connection con = (Connection) konek_nasabah.GetConnection();
                java.sql.Statement st = con.createStatement();
                ResultSet res = st.executeQuery(sql);  
            while (res.next()){
                    txtNama.setText(res.getString("nama"));
                    txtNIK.setText(res.getString("nik"));
                    txtTelp.setText(res.getString("no_telp"));
                    txtAlamat.setText(res.getString("alamat"));
                    txtKerja.setText(res.getString("pekerjaan"));
                    txtPinjam.setText(res.getString("jumlah_pinjaman"));
                    txtAngsuran.setText(res.getString("angsuran"));
                    txtNopol.setText(res.getString("nopol"));
                    txtKendaraan.setText(res.getString("kendaraan"));
                    txtTahun.setText(res.getString("tahun"));
                    txtBpkb.setText(res.getString("no_bpkb"));
                    txtStnk.setText(res.getString("nama_stnk"));
                    jTempo.setText(res.getString("jatuh_tempo"));              
                
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // update data nasabah yangs sudah ada
        
        String pk = txtPK.getText();
        String nama = txtNama.getText();
        String nik = txtNIK.getText();
        String telp = txtTelp.getText();
        String alamat = txtAlamat.getText();
        String kerja = txtKerja.getText();
        String pinjam = txtPinjam.getText();
        String angsuran = txtAngsuran.getText();
        String nopol = txtNopol.getText();
        String kendaraan = txtKendaraan.getText();
        String tahun = txtTahun.getText();
        String bpkb = txtBpkb.getText();
        String stnk = txtStnk.getText();
        String jeniskelamin =  (String) cbJK.getSelectedItem();
        String tenor =  (String) cbTenor.getSelectedItem();
        String surveyor =  (String) cbSurvey.getSelectedItem();
        String kolektor =  (String) cbKolektor.getSelectedItem();
        String tempo = jTempo.getText();
        
        try{
            
            String sql = " UPDATE `nasabah` SET `no_pk`='"+pk+"',`nama`='"+nama+"',`nik`='"+nik+"',`jenis_kelamin`='"+jeniskelamin+"',`no_telp`='"+telp+"',`alamat`='"+alamat+"',`pekerjaan`='"+kerja+"',"
                    + "`jumlah_pinjaman`='"+pinjam+"',`tenor`='"+tenor+"',`angsuran`='"+angsuran+"',`jatuh_tempo`='"+tempo+"',`nopol`='"+nopol+"',`kendaraan`='"+kendaraan+"',`tahun`='"+tahun+"',`no_bpkb`='"+bpkb+"',`nama_stnk`='"+stnk+"',`surveyor`='"+surveyor+"',`kolektor`='"+kolektor+"'WHERE `nasabah`.`no_pk`= '" +pk+ "'";
            Connection con = (Connection) konek_nasabah.GetConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil DiUpdate!");
        }catch (Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbJK;
    private javax.swing.JComboBox<String> cbKolektor;
    private javax.swing.JComboBox<String> cbSurvey;
    private javax.swing.JComboBox<String> cbTenor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTempo;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtAngsuran;
    private javax.swing.JTextField txtBpkb;
    private javax.swing.JTextField txtKendaraan;
    private javax.swing.JTextField txtKerja;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNopol;
    private javax.swing.JTextField txtPK;
    private javax.swing.JTextField txtPinjam;
    private javax.swing.JTextField txtStnk;
    private javax.swing.JTextField txtTahun;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
